### ISSUE TITLE
Allow "<< Back" menu localization

### ISSUE THREAD

**Issue by thingles** [thingles/foreground#100]
This menu is added via Javascript for small screens. It is currently always in English.

**Comment by Hutchy68** [comment]
Piece of cake for v2.0+. Foundation allows data-options in nav. Already coded it, will push it as a patch for v2.0. Will need localisation for other languages.

```
<nav class="top-bar" data-topbar role="navigation" data-options="back_text: <?php echo wfMessage( 'foreground-menunavback' )->text(); ?>">
```

**Comment by Hutchy68** [comment]
Fixed, closing.
