### ISSUE TITLE
Could foreground be integrated with VisualEditor?

### ISSUE THREAD

**Issue by nomu13** [thingles/foreground#154]
http://www.mediawiki.org/wiki/VisualEditor

WYSIWYG VisualEditor is supplied by Vector skin. It would be very nice to use VisualEditor in Foreground.

Is this possible?

Thank you for reading this.

**Comment by ckoerner** [comment]
@wottem put [their code up](https://github.com/Wiki-Org/Forground-VisualEditor-patch) that patches this in. Any chance we could add that to the project?

Also of note, VisualEditor has come a long way in the interim 9 months. We use it in production and it's been really successful in getting more folks to contribute.

**Comment by pepijng** [comment]
The fix works, the only issue i have now is that dialog boxes are not showing up correctly.

**Comment by pilondg** [comment]
Hi, we have had some troubles to with getting Visual Editor to work on Foreground, The patch from Wess and setting the LocalSettings.php. (Version MW 1.25), any help would be greatly appreciated.
