### ISSUE TITLE
Skin CSS overrides direction set by a template

### ISSUE THREAD

**Issue by NatashaBrown** [thingles/foreground#156]
On this page a template sets dir="rtl", but it is overridden by the skin: http://wikitranslate.org/wiki/Colours_2/Arabic

**Comment by Hutchy68** [comment]
Add to foreground.css

**Comment by Hutchy68** [comment]
need to add

```
[dir=ltr] * { direction: ltr; }
[dir=rtl] * { direction: rtl; }
[dir=ltr] { direction: ltr; }
[dir=rtl] { direction: rtl; }
```

to `assets/stylesheets/foreground.css`

**Comment by Hutchy68** [comment]
Merged into `foreground.css` closing.
