### ISSUE TITLE
Is there any way to make a sticky footer?

### ISSUE THREAD

**Issue by sjwiki** [thingles/foreground#166]
I have tried in vain to get the footer to be stuck to the bottom of the page, using this http://ryanfait.com/resources/footer-stick-to-bottom-of-page/

However, for some reason even though I wrap the whole page except the footer in a div https://github.com/sjwiki/foreground/blob/develop/Foreground.skin.php#L60 add the padding https://github.com/sjwiki/foreground/blob/develop/Foreground.skin.php#L187 and so on, it doesn't work. 

Is this a Foundation thing I'm missing?

**Comment by Hutchy68** [comment]
Closing, this issue has not had any activity in almost 3 years. Re-Open if needed.
