### ISSUE TITLE
"Actions" menu is a bit buggy

### ISSUE THREAD

**Issue by sjwiki** [thingles/foreground#168]
When I visit http://wikitranslate.org/, https://wikiapiary.com/, and/or my own site I have a number of problems using the "Actions" menu:

1. On mobile it _almost never_ works, I have tried all three sites (on my site with various attempts at fixing) over the last 3-4 days, I have managed to see the menu 3-4 times max on my phone. Could this be a z-index issue?

2. It looks a bit wrong compared to the non-develop branch (as do all menus), is it easy to fix the icons so they are on the same line as the text? (See screenshot below for what I mean.) Wikiapiary is the only one of the three that doesn't have this issue, presumably they are using the master branch.

3. On PC it often appears completely outside the visible window if the window is small, you have to scroll to the right to see it. I discovered this because I was trying to figure out why it doesn't work on mobile screens. Below is an example from wikitranslate what you get when you hover over it and scroll to the right:

Hover over "Actions" | Notice scrollbar appears, scroll to right
------------ | -------------
![screenshot - 310814 - 09 39 03](https://cloud.githubusercontent.com/assets/8448480/4101437/83fe0aea-30ea-11e4-82ac-8d2d016b3d6a.png) | ![screenshot - 310814 - 09 39 45](https://cloud.githubusercontent.com/assets/8448480/4101440/97114372-30ea-11e4-8a6d-8898a9a214a2.png)

I think these are all related, so I have put them together, apologies if you prefer them separate.

Thanks for your help so far. :+1:

**Comment by Hutchy68** [comment]
Closing this, reference #269 from this point forward.
