### ISSUE TITLE
Specify a LICENSE for project

### ISSUE THREAD

**Issue by thingles** [thingles/foreground#185]
Make sure and include references to licenses for dependencies:
- [ ] Foundation
- [ ] Font Awesome

**Comment by Hutchy68** [comment]
@kghbln could you do two PRs for this? One against develop branch and one again the release/1.x branch?

**Comment by kghbln** [comment]
> @kghbln could you do two PRs for this? One against develop branch and one again the release/1.x branch?

It will be BSD-2-Clause, will it?

**Comment by kghbln** [comment]
Done for develop with https://github.com/thingles/foreground/pull/289.

**Comment by Hutchy68** [comment]
Thanks @kghbln closing issue now.
