### ISSUE TITLE
Usage of H tags is bad for SEO

### ISSUE THREAD

**Issue by nikrolls** [thingles/foreground#188]
Currently this theme uses an H1 tag around the site name, and an H2 tag around the page title. Apart from the fact that this makes the page title look the same as all the primary headers on the page, it's also bad for SEO. Search Engines look for the page title in the H1 tag (there should only ever be one H1) and will rank a site lower if all pages appear to have the same title. 

Proposed changes:
- The site name should be wrapped in a DIV or SPAN rather than an H1.
- The page title should be wrapped in an H1 rather than an H2.

**Comment by Hutchy68** [comment]
Working on this. Will probably call for a change to the page title size. H1 is huge 😉

**Comment by Hutchy68** [comment]
Fixed, but left H1 size will leave it up to user to reduce
