### ISSUE TITLE
Orbit or Slick carousels?

### ISSUE THREAD

**Issue by sjwiki** [thingles/foreground#193]
Has anybody managed to get the [Orbit](http://foundation.zurb.com/docs/components/orbit.html) (which is part of Foundation) or the [Slick](http://kenwheeler.github.io/slick/) (which Foundation reccommends) carousel working? I tried both but I don't have as much experience as you do. I have tried doing both by implementing them as [Mediawiki tag extensions](https://www.mediawiki.org/wiki/Manual:Tag_extensions/Example), but I have failed so far.

Any ideas or pointers appreciated. :smile:

**Comment by Hutchy68** [comment]
The gray bar/line might be from `pre` CSS. Need to add a initial CSS for `pre` with a drilldown from orbit class to reset the class. Orbit uses the `pre` tags for the captions.

**Comment by Hutchy68** [comment]
Found and will fix. There is a margin adjustment for ul in CSS content-text which is being passed to the orbit sliders as they use `ul` tag.

```
#mw-content-text .orbit-container ul {
    margin: 0;
}
```

**Comment by Hutchy68** [comment]
Orbit will stay as the default since it is built in and will work with mediawiki markup just fine. You can also control, speed, stop, play, etc from `MediaWiki:Foreground.js` with the appropriate JS directed at Orbit.

**Comment by Hutchy68** [comment]
Fixed margin bug. Closing.
