### ISSUE TITLE
Option of adding a link to a "Special page" to the top bar

### ISSUE THREAD

**Issue by NatashaBrown** [thingles/foreground#205]
We have a "Translations" page on WikiTranslate http://wikitranslate.org/wiki/Translations:What_is_it_1

One goes to the page via "❱ LANGUAGES ❰" from every page of the lessons for now:
*http://wikitranslate.org/wiki/What_is_it_1
*http://wikitranslate.org/wiki/What_is_it_1/Russian
*http://wikitranslate.org/wiki/What_is_it_1/Greek

It would be nice if we move the link to the lessons in different languages to the top bar of the site. - It's just an idea.

**Comment by Hutchy68** [comment]
closing as navigation is handled by MediaWiki core.
