### ISSUE TITLE
Preference desgn update

### ISSUE THREAD

**Issue by paladox** [thingles/foreground#210]
Hi I think Preference needs an updated design because if you go here https://wikiapiary.com/wiki/Special:Preferences it is laid out in it shows it in full and doesn't have a nice look. we cold make it have a design as it does in vector or have better design.

**Comment by paladox2015** [comment]
@Hutchy68

**Comment by Hutchy68** [comment]
Not an easy task because of the way Mediawiki outputs the preferences. I've been using this, but you have to make sure CSS is allowed in preferences (the security fix in core which now has an options to allow).

```
/*Fixes for User Preferences Pages*/
#preftoc li a {
color: white;
padding: .25em .5em;
}
#preftoc li a:hover {
background: aqua;
color: white;
}
#preftoc li {
margin: 2px;
display:inline-block;
float: none;
padding: 1px;
position: relative;
list-style-type: none;
list-style-image: none;
z-index: 3;
border-radius: 3px;
font-size: .85em;
background: #142849;
border:0;
color: white;
}
 
#preftoc li a {
color: white;
}
 
#preftoc li a:hover {
background: #2ba6cb;
}
ul#preftoc {
margin: auto;
text-align: center;
}
#preftoc > li.selected {
background: #2C58A1;
box-shadow: 2px 2px 5px 2px rgba(50, 138, 64, 0.54);
}
#preftoc li.selected a {
cursor: default;
text-decoration: none;
}
#preferences table {
min-width: 100%;
}
#preftoc {
    margin: 0;
	padding: 0;
	width: 100%;
	clear: both;
}
#preftoc a:active {
	display: block;
	color: #000;
	padding: 0 .7em;
	position: relative;
	text-decoration: none;
}
#preftoc li.selected a {
	cursor: default;
	text-decoration: none;
}
#preferences {
	margin: 0;
	clear: both;
	background-color: #FFF;
	border: none;
}
.prefsection {
	border: none;
	padding: 0;
	margin: 0;
}
.prefsection legend {
	font-weight: bold;
}
.prefsection table, .prefsection legend {
	background-color: #F9F9F9;
}
#preferences legend.mainLegend {
display: none;
} 
#preferences fieldset legend {
	font-weight: bold;
	padding: 0 .25em;
	margin: 0;
	margin: 0 .25em 0 1em;
	background:#FFF;
}
```

Just add it to ```MediaWiki:Foreground.css``` to test it. Colors are hard set, if it is added to ```foreground.css``` we should make it more agnostic and note in docs how to style with color.

**Comment by paladox2015** [comment]
Hi it should be added to foreground. Like vector is.

**Comment by paladox2015** [comment]
This 

$GLOBALS['wgResourceModuleSkinStyles']['vector'] = array(
   'mediawiki.special.preferences' => 'assets/stylesheets/mediawiki.special.preferences.less',
   'remoteSkinPath' => 'foreground',
   'localBasePath' => __DIR__,
);

Would be added to foreground.php

**Comment by Hutchy68** [comment]
yep, except it can't be ```.less``` because Foundation doesn't support ```.less```

Anyway, we just nee to decide what looks good and go with it. We can't use the Vector style because it doesn't look right in a mobile view. So we need our own.

![image](https://cloud.githubusercontent.com/assets/3527469/5987941/c6f63c6c-a914-11e4-9acc-44db34c496ea.png)

**Comment by paladox2015** [comment]
Ok sorry I forgot to change it to .css. And ok it was just a suggestion on how it would look like.

**Comment by Hutchy68** [comment]
No problem. Pill menu style is probably going to be the way to go, centered. As I said it'll be something will have to decide on and be specific to the skin.

**Comment by paladox2015** [comment]
Ok.

**Comment by Hutchy68** [comment]
This has a fix for now similar to the way vector and monobook handle it. Using pills which center on mobile.

![image](https://cloud.githubusercontent.com/assets/3527469/25161707/98322464-248b-11e7-9d61-9ae2884f62f5.png)

**Comment by Hutchy68** [comment]
Fixed, closing
