### ISSUE TITLE
Font download failure

### ISSUE THREAD

**Issue by AerosAtar** [thingles/foreground#222]
Firefox (and, to a lesser extent, Chrome and IE) has an issue where it fails to download the font and so doesn't display any of the icons correctly.

A very easy fix has been identified in a number of locations, https://github.com/cdnjs/cdnjs/issues/755 being one of them.

The fix is to add the following to the start of the font-awesome.css file (before the @font-family call):

`<FilesMatch ".(ttf|otf|woff)$">
    Header set Access-Control-Allow-Origin "*"
</FilesMatch>`

**Comment by Hutchy68** [comment]
This is a server setup issue. For fonts hosted locally you need to allow the MIME type or change the default from html out to plain/text. The best is to add the font MIME types to the server in .htaccess or the main apache or nginx hosts file.
