### ISSUE TITLE
 Add an Icon for CiteThisPage in the dropdown menu 

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#232]

**Comment by Hutchy68** [comment]
Assuming can still use MediaWiki:Forground.js without issue in 1.26 should be able to do something similar to `$('li#citethispageID').prepend('<div class="drop-icon"><i class="fa fa-university fa-fw"></i></div>')`

**Comment by kghbln** [comment]
Probably I will give this a shot soon after compat with 1.26 is regained.

**Comment by paladox** [comment]
MediaWiki 1.26 support has been added now.

**Comment by Hutchy68** [comment]
Since CiteThisPage is now part of a MW release, adding support.

I don't know if we show use this one on the university icon

![citethispageicon](https://cloud.githubusercontent.com/assets/3527469/11982115/7d7c7200-a976-11e5-8ccc-97cb5bbcd566.PNG)

**Comment by paladox** [comment]
That icon looks good. Did we have an icon for cite before the changed it all.

**Comment by Hutchy68** [comment]
done, see #272
