### ISSUE TITLE
Broken as of 1.26 or later: "style module should define its position explicitly"

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#233]
[Copied from extension's talk page](https://www.mediawiki.org/wiki/Topic:Stqdtgi52lozd65p):

I updated Mediawiki 1.25 to 1.26.

But, When I displayed foreground skins, there shows some warning at the top of the display.

"style module should define its position explicitly"

Moreover, there are css or javascript trouble. I cant click menu links.

I researched the cause, and i know that as for version 1.26 custom skins needs "skin.json" which define its positions.

Is there any plan to update Foreground skin forcorresponding 1.26? Or, is there any modification to solve this problem?

Thanks.

@thingles FYI

**Comment by kghbln** [comment]
Hmm, the position is defined in [line 64] (https://github.com/thingles/foreground/blob/develop/foreground.php#L64). Perhaps it how has to be defined in line 38 before specifying the styles, at least this [information](https://www.mediawiki.org/wiki/MediaWiki_1.26#Module_position_must_be_added_in_ResourceModules) reads like it.

A "skin.json" is not yet? mandatory with 1.26+.

**Comment by kghbln** [comment]
Well this pull request contains the fix: https://github.com/thingles/foreground/commit/9adf0c3f63a4fe7963a9c27f3e1e5c58bbd15b5d. So we need a new release.

**Comment by kghbln** [comment]
Well, the commit https://github.com/thingles/foreground/commit/9adf0c3f63a4fe7963a9c27f3e1e5c58bbd15b5d did not fix anything. Still broken for MW 1.26. Again undocumented breaking bullsh. Perhaps [this helps](https://www.mediawiki.org/wiki/Topic:Sthbopqp2podznfo). Thus reopening. 

@thingles FYI

**Comment by Hutchy68** [comment]
I can't look into this until tomorrow unless @paladox has time to look. Agree b/c without docs and it does look like a lot of skins are reporting issues with 1.26.

**Comment by kghbln** [comment]
Yeah. :(

**Comment by paladox** [comment]
Please check a patch I uploaded here https://github.com/thingles/foreground/pull/235

**Comment by paladox** [comment]
I haven't tested but hope it fixes the problem.

**Comment by paladox** [comment]
We could possibly split styles and script so that there are two different resource loading one a style and the other a script so that way the style will be top and bottom could be script.

**Comment by kghbln** [comment]
I have asked for a [field test](https://www.mediawiki.org/w/index.php?title=Topic:Stqdtgi52lozd65p&topic_showPostId=stsy52651ud48iz2#flow-post-stsy52651ud48iz2).

**Comment by paladox** [comment]
Thanks and I also have https://github.com/thingles/foreground/pull/238 which may fix the problem and improve the performance.

**Comment by paladox** [comment]
I also tested that user may be using version 1.1 instead of using 1.2 alpha. I suggest we should realease 1.2. It works for me. Except echo is under personal bar instead of next to action button but that's because of a update to echo which needs css updating on this skin.

**Comment by Hutchy68** [comment]
Thanks @paladox.  I'll look into it in the next few days it's been one of those weeks. We had a loss in the family. The past few days have been really hard.

**Comment by paladox** [comment]
This has been done @kghbln could you close this. I want to make sure that I have done what this task asks.

**Comment by kghbln** [comment]
@paladox Accorting to the [field test](https://www.mediawiki.org/w/index.php?title=Topic:Stqdtgi52lozd65p&topic_showPostId=su0e1g0iek3p1buw#flow-post-su0e1g0iek3p1buw) there is still an issue. I do not have a MW 1.26 at hand so I cannot test right now.

**Comment by Hutchy68** [comment]
@kghbln develop should work now it sound like #243

**Comment by kghbln** [comment]
@Hutchy68 You are our hero! Kudo!

**Comment by Hutchy68** [comment]
Not me @paladox for getting the patches PRs

**Comment by paladox** [comment]
Hi could you get the user to update to the very latest from develop branch since the position has been applied. Also skin.json has been added for mw 1.25+ compat.

**Comment by kghbln** [comment]
This particular field test does not get us anywhere. In the meantime I suspect that the wiki in question has multiple other issues and foreground is just the first thing to realise it. Anybody else already on MW 1.26?

**Comment by Hutchy68** [comment]
I suspect caching is the issue.  I think even if the user is logged in now and there's no page change they will be served a cache file for example.  It's only when the actual page changed in content will I logged in user get the most recent version .

**Comment by Hutchy68** [comment]
I'm going to reopen this issue as there is still ongoing conversations, but please note, this is considered fixed in 1.2.

I am testing and now using 1.2 from develop branch on one of my wikis. It is the default skin and it works without any issues.

**Comment by paladox** [comment]
I've been testing using mediawiki 1.27 and all works for me.

**Comment by Hutchy68** [comment]
Awesome! I've tested it on a production 1.23 and a development 1.26 w/10 extensions. @thingles let me know he will try to update WikiApiary tonight. I am 99% certain the original reporter of a 1.26 problem is viewing pages cached in html, which of course will still have the missing html from the dropdown button.

**Comment by kghbln** [comment]
How cool is this. Thanks a ton for the great work that has been done! :+1:  Yeah, hopefully it is just a caching issue.

**Comment by Hutchy68** [comment]
I saw the field test post on MW Foreground discussion page. Considering this closed now. Seems caching was his issue. If they are modifying the skin files, I see no way for us to help. If they are modifying because we are missing something the site using Foreground needs to do, then they must create an issue here and let us know.

**Comment by kghbln** [comment]
> If they are modifying because we are missing something the site using Foreground needs to do, then they must create an issue here and let us know.

Sounds like a very reasonable approach to me. Thanks for your support!
