### ISSUE TITLE
Fix echo support

### ISSUE THREAD

**Issue by paladox** [thingles/foreground#237]
Echo has a majour update In https://git.wikimedia.org/commitdiff/mediawiki%2Fskins%2FMetrolook.git/985b4b586f693045feeb9a5ea169ef80858a07cc which is breaking the css in this skin for echo. Echo is now in the usermenu instead of next to action button. The css needs to be changed to fix this problem.

**Comment by Hutchy68** [comment]
Looking at this now, I'll post back in a few.

**Comment by paladox** [comment]
Ok thanks.

**Comment by Hutchy68** [comment]
This one is going to take a bit of time. Echo is now attaching as a keyed item in personal instead of a js attachment to a div ID. :angry:

**Comment by paladox** [comment]
Oh ok. well you could do what I did in metrolook

to split echo out of personal bar.

https://github.com/paladox/Metrolook/blob/master/MetrolookTemplate.php#L31

to 

https://github.com/paladox/Metrolook/blob/master/MetrolookTemplate.php#L31

https://github.com/paladox/Metrolook/blob/master/MetrolookTemplate.php#L171

to

https://github.com/paladox/Metrolook/blob/master/MetrolookTemplate.php#L178

https://github.com/paladox/Metrolook/blob/master/MetrolookTemplate.php#L346

to

https://github.com/paladox/Metrolook/blob/master/MetrolookTemplate.php#L350

https://github.com/paladox/Metrolook/blob/master/MetrolookTemplate.php#L850

to

https://github.com/paladox/Metrolook/blob/master/MetrolookTemplate.php#L865

css file

https://github.com/paladox/Metrolook/blob/master/components/personalMenu.less#L94

to

https://github.com/paladox/Metrolook/blob/master/components/personalMenu.less#L105

**Comment by paladox** [comment]
The tag was changed from notifications to notifications-alert

**Comment by paladox** [comment]
@Hutchy68 https://github.com/thingles/foreground/blob/develoAlsp/assets/scripts/foreground.js#L14 

pt-notifications needs changing to pt-notifications-alert

Also the div id is #echoNotifications I am not sure weather it has always been like that.

**Comment by paladox** [comment]
You should follow the php code that I have in the links above which would make the problem easier to fix in future.

**Comment by paladox** [comment]
Css for echo for this skin here is here https://github.com/thingles/foreground/blob/develop/assets/stylesheets/foreground.css#L727

**Comment by Hutchy68** [comment]
Yep, probably should do a little more but I added the fixes for now to #241. `foreground.js` and `foreground.css` tweaks. I can see there will be a small issue going forward because the size of the pop up is now hard set as a css element.

**Comment by Hutchy68** [comment]
Fixed with #241, we can open another issue if needed to work on better integration after we get 1.2 released. Closing.
