### ISSUE TITLE
disclaimers link is invisible in sidebar menu

### ISSUE THREAD

**Issue by CJTharp** [thingles/foreground#239]
This is a very small issue, but a strange one. If I add a link to the disclaimers in the sidebar the link will be invisible in the pull menu. It only happens with the disclaimers link. For the record I erased the links at the bottom for a more pleasing look. see photos:
![disappearing disclaimers](https://cloud.githubusercontent.com/assets/9703601/11608890/9e6b0066-9b2b-11e5-93aa-8d78d00483d5.png)
![side bar inputs](https://cloud.githubusercontent.com/assets/9703601/11608891/9e6b0746-9b2b-11e5-910a-91cfaaf15981.png)

**Comment by Hutchy68** [comment]
How many links are in the drop down? I can't replicate this issue. Also, what version of MW and Foreground are you using?

**Comment by Hutchy68** [comment]
Can't replicate, no answer closing. Re-open if needed.
