### ISSUE TITLE
Run new inspection at https://scrutinizer-ci.com/g/thingles/foreground/inspections/2f11b892-bfa0-4239-9af1-086515a6178a

### ISSUE THREAD

**Issue by paladox** [thingles/foreground#240]
Please run a new inspection at https://scrutinizer-ci.com/g/thingles/foreground/inspections/2f11b892-bfa0-4239-9af1-086515a6178a to migrate it too the new model. 

for develop and master branch

**Comment by Hutchy68** [comment]
Done, this should have been closed.
