### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by paladox** [thingles/foreground#242]
After 1.2rc is released we should start testing 1.2 for main release testing what is broken and fixing it before main release.

**Comment by Hutchy68** [comment]
see issue #243 which would be a blocker. I believe the problem crept in months ago.

**Comment by paladox** [comment]
This has https://github.com/thingles/foreground/issues/243 been fixed now.

**Comment by kghbln** [comment]
Now that recent issues have been solved tagging 1.2.0 for semver (more clean with three digits) and releasing 1.2 for marketing (more easy for users) sounds like a good plan.

**Comment by paladox** [comment]
Can be released at https://github.com/thingles/foreground/releases now since the version was changed to 1.2.0.

All the changes need back porting to 1.x branch.

**Comment by Hutchy68** [comment]
Done

**Comment by paladox** [comment]
Thanks.
