### ISSUE TITLE
Update wikiapiary to mediawiki 1.27

### ISSUE THREAD

**Issue by paladox** [thingles/foreground#248]
Please update wikiapiary to mediawiki 1.26 and please also use the latest update to develop branch since it includes some fixes.

**Comment by thingles** [comment]
I’m not sure about upgrading my wiki farm to 1.26 yet. Sounded a bit sketchy so far.

**Comment by paladox** [comment]
Ok.

**Comment by paladox** [comment]
Maybe wait until there is an 1.26.x update like 1.26.1.

1.26 seems to be good if they haven't released a patch yet.

**Comment by paladox** [comment]
Could the skin be updated since it would be able to support mediawiki 1.25 which the website is using so it would use the skin.json files.

It includes fixes.

**Comment by paladox** [comment]
Skin was updated on that website but is using commit 195f91e so it is using the version from October 25 not from the current commit. So doesn't include al The fixes.

@thingles could the skin on the website be updated to commit 98d6e7c2e7a696a518459153ad1274b14cb113c8 Please

**Comment by paladox** [comment]
@thingles could we try out foreground 2.0 on wikiapiary once https://github.com/thingles/foreground/pull/274 is merged.

Reasons is it now uses foundation5. Includes many bug fixes. Also action drop down button now uses built in foundation support meaning it will work straight away without any js fallback that we would have to do it our selfs.

**Comment by paladox** [comment]
@thingles could you create a test wiki for wikiapiary where we could try the 2.0 update on it and fix the issues we find.

**Comment by kghbln** [comment]
This is not about Wikiapiary this is about having a testing site running latest code. The [Foreground homepage](http://foreground.wikiproject.net/wiki/Special:Version) could serve as a testing site or the [Semantic MediaWiki](http://sandbox.semantic-mediawiki.org/wiki/Special:Version). Both run latest stable of MediaWiki and Foreground. Since sandbox offers a much wider variety of different extensions I go for this one. I could update Forground to "albert".

**Comment by Hutchy68** [comment]
@thingles 1.27 works just fine with v1.2 running on it. Could you do the upgrade to 1.27 so we can close this. I don't think v2.0 will be usable on wikiapiary because of the formation of tabs unless you go in and change all the code of the templates.

**Comment by paladox** [comment]
@Hutchy68 hi, maybe we could include a new config just for wikiapriary to allow us to upgrade the skin on there to 2.x. We should either update wikiapriary to 1.27 or 1.28 or wait for 1.29.

**Comment by Hutchy68** [comment]
I don't know what you propose, but Wikiapiary relies heavily on tabs. Foreground v1.2 works on 1.27 and even 1.28. It would be up to @thingles but I doubt he would want to create a special configuration just for Wikiapiary.

We could backport as much as possible, like Page Indicators, Echo fixes, etc. into v1.2, bump it up to 1.3 and at the same time eliminate the shim and make the skin use `wfSkinLoad` giving a nudge to update MW versions to 1.27.

**Comment by paladox** [comment]
Ok.

**Comment by kghbln** [comment]
This issue is not a issue for foreground but for @wikiapiary. I'd close this here.
