### ISSUE TITLE
Make 1.2 release

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#250]
@thingles and @Hutchy68 

Now that recent issues have been solved tagging 1.2.0 for semver and releasing 1.2 for marketing sounds like a good plan.

**Comment by paladox** [comment]
Done by https://github.com/thingles/foreground/pull/249

The release note file would need updating with a release date next to it when ever it is released.

**Comment by kghbln** [comment]
Dupe to https://github.com/thingles/foreground/issues/242
