### ISSUE TITLE
Using SemVer Going Forward

### ISSUE THREAD

**Issue by Hutchy68** [thingles/foreground#253]
I am adding this as an issue for discussion.

Should Foreground use SemVer starting with the 1.2 release? See http://semver.org/

**Comment by kghbln** [comment]
:+1:

**Comment by Hutchy68** [comment]
:+1:

**Comment by thingles** [comment]
Everything should, including Foreground. ;-)

**Comment by paladox** [comment]
Ok done in https://github.com/thingles/foreground/pull/249

**Comment by Hutchy68** [comment]
Kind of a no brainer, using SemVer from this point on.
