### ISSUE TITLE
Use gerrit as localisation update

### ISSUE THREAD

**Issue by paladox** [thingles/foreground#262]
@Hutchy68 Could we create a repo at gerrit on Wikimedia for use for localisation updates. We would then merge the i18n update here.

**Comment by kghbln** [comment]
In the meantime translatewiki.net also supports GitHub as a code repo. I think it is just a matter of granting commit access to this repo to @Nikerabbit and @Siebrand and having decent "en.json" and "qqq.json" files for this to work.

**Comment by Nikerabbit** [comment]
Above is correct.

**Comment by kghbln** [comment]
@Hutchy68 After https://github.com/thingles/foreground/pull/293 is merged we could give this issue a shot. Will be cool.

**Comment by Hutchy68** [comment]
I would love to do this. I don't know if I have permissions to add collaborators. I will check otherwise @thingles will have to add @Nikerabbit and @Siebrand

**Comment by kghbln** [comment]
In the meantime we also have to  add @translatewiki

**Comment by thingles** [comment]
I've added @Nikerabbit @siebrand and @translatewiki as collaborators.

**Comment by kghbln** [comment]
> I've added @Nikerabbit @siebrand and @translatewiki as collaborators.

Awesome!

**Comment by Nikerabbit** [comment]
FWIW only @translatewiki is sufficient nowadays.

More info: https://translatewiki.net/wiki/Setup_of_a_new_project

**Comment by kghbln** [comment]
> FWIW only @translatewiki is sufficient nowadays.

Ah, I see. I guess you both may also be equally trusted. I guess all the rest is covered. As soon as foreground is active on twn you could drop a note here for this issue to be closed.

**Comment by Nikerabbit** [comment]
Could you file a request on https://translatewiki.net/wiki/Support or #TWN Phabricator, or submit a patch (sorry if you have already done any of these and I have not seen it) so that it does not get forgotten.

Please allow multiple days for processing.

**Comment by kghbln** [comment]
> Please allow multiple days for processing.

No worries. [Now on Phabricator](https://phabricator.wikimedia.org/T163448).

**Comment by kghbln** [comment]
Done with https://gerrit.wikimedia.org/r/#/c/395021/.

@Hutchy68 This may now be closed. :)

**Comment by Hutchy68** [comment]
Thanks everyone
