### ISSUE TITLE
Common CSS Should be distinguished

### ISSUE THREAD

**Issue by victoroux** [thingles/foreground#267]
".label" is very common. When exporting to this style we had a bit of trouble fixing that all up :) Would have probably been easier if it were coded in as ".FoundationLabel" or something. Thank you for all the hard work everyone -- really nice theme.

**Comment by Hutchy68** [comment]
label is common, yes. Foreground uses the default Foundation css and js for its framework. Sorry you had trouble. Please issue a PR if you like, but it can't change the core Foundation files. It makes it too hard to update the Foundation code when a new version or fix is issued by Zurb.
