### ISSUE TITLE
Actions Dropdown Buggy

### ISSUE THREAD

**Issue by victoroux** [thingles/foreground#269]
Only exits dropdown if clicking on actions bar or crossing over the contents of the dropdown, will not self-close if simply away from actions bar after triggering unlike top-bar dropdowns.

**Comment by paladox** [comment]
I noticed if you hover your mouse over it and then want to close it if you go to the right it wont close but if you go to the left it will.

**Comment by paladox** [comment]
@Hutchy68 Do you have an idea on how to fix this. I am currently testing foundation 5 with this skin and can reproduce the same problem.

**Comment by Hutchy68** [comment]
Yes, it's buggy. Use the native foundation dropdown class but...  And it's a big but...  Foundation 4 was half baked in with classes that handled left and right drop down ears at the top. 4 works but if the on hover button is far enough away from the browser edge that aligns to the ear left not right. 5 there is more control.  

 I cannot do anything right now but if you can wait about three or four hours I'll put something up in my fork.

**Comment by paladox** [comment]
Ok thanks. I am trying to fix the foundation5 branch here so we can use it. I have to change some classes names and js. I have switched to using the foundation js for opening and closing action.

**Comment by Hutchy68** [comment]
Actions on hover is now native in develop branch for the upcoming Foreground 2.0. Although Foundation 5 has a regression and the menu now opens to the left as a work around. see #272
