### ISSUE TITLE
Prepare foundation5 branch to be merged in develop branch

### ISSUE THREAD

**Issue by paladox** [thingles/foreground#271]
Prepare foundation5 branch to be merged in develop branch

Checklist:

- [ ] Make sure everything works and is stable
- [ ] Merge into develop branch
- [ ] Release 2.0.0 once everything is stable.

**Comment by thingles** [comment]
@Hutchy68 @paladox just a thought, but Foundation 6 just came out. Would life be better for us at all if we just jumped straight to that and skip 5?

**Comment by paladox** [comment]
@thingles I just relised that foundation6 was released. But upgrading to it broke the whole skin so a rewrite would be needed. It isen't like foundation5 which didn't break the skin much just a few classes needed to be renamed but in foundation6 I am not sure what needs to be changed since they haven't created a upgrading guide like they did for foundation5 when upgrading from foundation4 to 5. I would say let us upgrade to foundation5 first then foundation6. Since foundation6 would need a lot of work.

**Comment by Hutchy68** [comment]
I'm sure you did but just asking anyway. You did get foundation six for sites not apps correct ?  I do know that they reduced the footprint of the framework so I'm sure there's going to be quite a few changes.

**Comment by Hutchy68** [comment]
http://zurb.com/university/lessons/how-to-re-create-top-bar-with-foundation-6 Yep a rework will be needed.

**Comment by paladox** [comment]
Yes I used the sites one.

**Comment by paladox** [comment]
Thanks for finding that. We could follow that but foundation6 may take a while like we did with foundation5 so I think we should ahead with foundation5 then 6.

Could there be a branch created for foundation 6 please.

**Comment by thingles** [comment]
Thank you both for looking into that. I hadn't done anything yet. I would recommend no branching or anything at all for Foundation 6 until we get a solid Foreground 2.0 based on Foundation 5. Then, once the dust has settled and then some, consider **if** Foundation 6 is desired.

**Comment by paladox** [comment]
Ok.

**Comment by Hutchy68** [comment]
Foundation 5 is now in the develop branch
