### ISSUE TITLE
JS wont load if your in another tab

### ISSUE THREAD

**Issue by paladox** [thingles/foreground#275]
When I go to another tab and whilst my website is loading and I go back the js dosent load. I have to refresh and stay on the same page until it loads.

Please fix this.

**Comment by Hutchy68** [comment]
I can't replicate this issue. What version of Foreground?

**Comment by Hutchy68** [comment]
Closing, can't replicate on various sites running Foreground. Server issue? Browser extension?

Reopen if needed.
