### ISSUE TITLE
Move Page not formatted correctly in the new Foundation 5 Foreground skin

### ISSUE THREAD

**Issue by CJTharp** [thingles/foreground#279]
New Name Line overlaps the Reason Line:

![move page problem](https://cloud.githubusercontent.com/assets/9703601/12252893/1e24185c-b890-11e5-952b-bb0bba7f595c.png)

**Comment by Hutchy68** [comment]
Version number? v1.2 or v2.0? I have not see this in move pages.

**Comment by Hutchy68** [comment]
Closing, I have looked at v2.0 in Chrome and Edge browser. Cannot replicate, see screen clip below.

reopen if needed

![image](https://cloud.githubusercontent.com/assets/3527469/25161478/2c3258c0-248a-11e7-8f0e-067c3ea56060.png)
