### ISSUE TITLE
Blocks show instead of icons

### ISSUE THREAD

**Issue by tobycoder** [thingles/foreground#283]
Hi there,

Foreground does only show blocks instead of icons. How can i fix it?

**Comment by ayazaslam27** [comment]
I am facing the same issue! Plus the top bar has an additional white top bar above it! How can I fix it?

**Comment by tobycoder** [comment]
Sorry but this has no stilo mate.... I'm still waiting for answer...

**Comment by Hutchy68** [comment]
See issue #222, server issue. Set MIME types on the server so fonts are not blocked by browser.
