### ISSUE TITLE
Add support for page status indicators

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#286]
MediaWiki 1.25 introduced [page status indicators](https://www.mediawiki.org/wiki/Help:Page_status_indicators) as described on this [help page](https://www.mediawiki.org/wiki/Manual:Skinning_Part_2#Page_status_indicators) to allow "foreground" be even more awesome an do things like [this one](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1313#issuecomment-239620150).

**Comment by Hutchy68** [comment]
Need to add `<?php echo $this->getIndicators(); ?>` only issue is this is only available in MW > 1.25. See issue  see issue #287 (Drop support for MW 1.23). Unless we check for version of MW, this will throw an exception error.

**Comment by Hutchy68** [comment]
closing
