### ISSUE TITLE
Drop support for MW < 1.25 with Foreground v2.0

### ISSUE THREAD

**Issue by Hutchy68** [thingles/foreground#287]
Should we drop support for MW installation under 1.25 with the release of Foreground v2.0? 

MW 1.23 support runs out in May 2017 and the last or next to last security update for 1.23 has just been released. There will be no more support for the LTS MW 1.23 so why should Foreground v2.0 support it?

**Comment by Hutchy68** [comment]
Since no one has commented on this issue, I am going under the assumption of support of Foreground v.2+ will not work with MW versions under 1.25. See PR# 286

**Comment by kghbln** [comment]
@Hutchy68 Just saw this. Yeah this is fine with me. We still have the "release/1.x" branch.

**Comment by kghbln** [comment]
Since we are dropping support for < MW 1.25 the release should rather be 2.1.0 than 2.0.1?!

**Comment by Hutchy68** [comment]
Thanks to @kghbln we can now close this issue. Foreground released version will support MW 1.25 +. MW 1.23 is set to lose support in approx 30 days. No sense in maintaining a compatibility for a MW version losing support.

**Comment by paladox** [comment]
@hutchy68 what about dropping support for mw 1.26 and lower as 1.25 and 1.26 are unsupported too.
