### ISSUE TITLE
Fixes for AddThis

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#295]
I guess Foreground needs AddThis fixes, too as in [pivot](https://github.com/Hutchy68/pivot/commit/3346f180581a902fda3ce8ffbad1dcc0975af370)

**Comment by kghbln** [comment]
@Hutchy68 I guess this one should go into 2.1.0 Will probably be a similar fix as the one for pivot.

**Comment by Hutchy68** [comment]
Yes this is the last milestone I need to complete as I’ve taking care of the other three. I just have not pushed them yet to here but the commit is pushed into my account on GitHub. Develop branch.

**Comment by Hutchy68** [comment]
Fixed, closing
