### ISSUE TITLE
Page Forms: icon for actions "formedit" and "formcreate"

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#298]
**Setup**
- MediaWiki 	1.27.2 (1c409c5) 01:42, 7 April 2017
- PHP 	5.6.30 (cgi-fcgi)
- MySQL 	5.6.28-76.1-log
- Semantic MediaWiki	2.5.1 (568d058) 01:52, 22 April 2017
- Page Forms	4.1 (7f1cec5) 19:13, 8 February 2017
- Foreground	2.1.0-alpha (c6b55e8) 14:05, 20 April 2017

**Issue**
The [Page Forms](https://www.mediawiki.org/wiki/Extension:Page_Forms) extension is quite popular in the semantic community. Thus it will be nice to support actions "formedit" and "formcreate" with a dedicated icon. The icon for both actions should be the same.

**Comment by Hutchy68** [comment]
Semantic forms used one `form_edit` and Page forms uses `formedit` as classes. I account for both now. Closing, reopen if needed.

**Comment by kghbln** [comment]
Working perfect! Thanks a lot!
