### ISSUE TITLE
Semantic MediaWiki: status indicators misaligned

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#299]
**Setup**
- MediaWiki 	1.27.2 (1c409c5) 01:42, 7 April 2017
- PHP 	5.6.30 (cgi-fcgi)
- MySQL 	5.6.28-76.1-log
- Semantic MediaWiki	2.5.1 (568d058) 01:52, 22 April 2017
- Foreground	2.1.0-alpha (c6b55e8) 14:05, 20 April 2017

**Issue**
Semantic MediaWiki comes with [usage count indicators](https://www.semantic-mediawiki.org/wiki/Help:Property_usage_count) which are misaligned on Foreground. So far I have not figured out how to fluff them.

**Screenshot**
![bildschirmfoto vom 2017-04-24 22-34-15](https://cloud.githubusercontent.com/assets/1104078/25357682/03b16670-293f-11e7-9d70-087e73d281d1.png)

**Comment by Hutchy68** [comment]
Thanks @kghbln do you have a live site I could see these on?

**Comment by kghbln** [comment]
> Thanks @kghbln do you have a live site I could see these on?

Now I have:
* [foreground](https://sandbox.semantic-mediawiki.org/w/index.php?title=Attribut:Has_page_fixed&useskin=foreground)
* [vector](https://sandbox.semantic-mediawiki.org/w/index.php?title=Attribut:Has_page_fixed&useskin=vector)
Note that on vector you can even see the icon signaling the protected status of the page.

If you register there I could make you an admin.

**Comment by Hutchy68** [comment]
Darn, I see what the issue is. I'll push out a fix tonight.

**Comment by Hutchy68** [comment]
Fixed and closing. Part of the issue was the introduction of .mw-indicator class. Older versions of SMW automatically floated right. Please check from develop branch and reopen if needed.

**Comment by kghbln** [comment]
@Hutchy68 Great! Semantic MediaWiki is working perfect now, however the Echo notification is now bellies up. :(

**Comment by Hutchy68** [comment]
Of course it is :( I'll take a look.

**Comment by Hutchy68** [comment]
Yikes, this will take a while. Something really weird going on. PS I hate echo ;-)

**Comment by kghbln** [comment]
> Yikes, this will take a while.

Yeah, if it was just some CSS voodoo but it looks like ... You should create an account and look at the user menu. Did not even report this. :|

**Comment by kghbln** [comment]
>  You should create an account

It has all happened. Now contributor, admin and crat.

**Comment by Hutchy68** [comment]
Thanks @kghbln 

I know what the issue is with echo... the Echo Developers!

Echo 1_27 release Jun 2016

```
<a href="/wiki/Special:Notifications" 
class="mw-echo-notifications-badge mw-echo-notification-badge-nojs 
oo-ui-image-invert oo-ui-iconElement oo-ui-iconElement-icon oo-ui-icon-bell" 
title="Your alerts">0
</a>
```

Echo 1_28 release Oct 2016

```
<a href="/wiki/Special:Notifications" 
class="mw-echo-notifications-badge mw-echo-notification-badge-nojs" 
data-counter-num="1" 
data-counter-text="1" 
title="Your alerts">1
</a>
```

`<rant>`

4 months later they have rewritten the whole output of the notification and messages. I'm starting to wonder if it is worth the time to have echo. The issue is, Echo developers do this:

- Design for vector / monobook (but mainly vector)
- Design for Wikimedia sites
- Have terrible documentation
- Completely disregard 3rd party wiki use
- Always have B/C in their releases, not even following core changes

Honestly, I think it is time for a decent Echo 3rd party fork or once and for all merge it into MW core and let the development of it be oversee by someone who knows what a b/c is.

`</rant>`

**Comment by kghbln** [comment]
@Hutchy68 You are definitively not the only one with an issue here. Now that you are writing this I remember that Echo was rewritten for MW 1.28. What I did  not have on my radar is that they oops did it again. :(

> Completely disregard 3rd party wiki use

Indeed there are people around that seem to believe that sharing knowledge is only possible on WMF wikis. The scope of WMF's core mission however lies much beyond this narrow interpretation.

**Comment by Hutchy68** [comment]
If you look on 1.28 now they have even changed the div ID from -messages to -notices. Why? IMHO that's the equivalent to core changing mw-content to mw-pagecontent to mw-content-of-page. They all mean the same thing but they don't programmatically. 

Whoever the lead developer is does not know the meaning of backwards compatibility nor do they understand the meaning of breaking changes.

At this point I don't even know if I can write anything that's going to be compatible for someone who's using 1.27 versus someone using 1.28.

**Comment by kghbln** [comment]
O_o

> At this point I don't even know if I can write anything that's going to be compatible for someone who's using 1.27 versus someone using 1.28.

Here I'd personally prefer 1.27 since this is LTS. Given the changes I'd start to worry about new versions as soon as MW 1.30-alpha is around. At the same time the docu should probably emphasize the focus on LTS versions. 

The only reason why sandbox is on MW 1.28 is to help SMW somehow cope with newer releases since it is one of the most popular extensions to MediaWiki. One the other hand: Forgeground as a skin has gotten pretty important nowadays too so not caring about regular releases of MW and the most popular extensions to it may not be a good idea after all.

**Comment by Hutchy68** [comment]
@kghbln Could you pull down the changes to the develop branch. This is going to be a process. I will have to setup a dedicated 1.28 with echo installed eventually but this is the start of looking at how to fix it. Ugh!

**Comment by kghbln** [comment]
> Could you pull down the changes to the develop branch. 

Done!

**Comment by Hutchy68** [comment]
Thanks @kghbln 

If you are still awake, the develop branch has one more update which I think will make 1.28 and 1.27 work.

**Comment by kghbln** [comment]
> If you are still awake

No, was already in sleepy land. Updated now.

>  I think will make 1.28 and 1.27 work.
 
Better but not quite, at least for 1.28+

**Comment by Hutchy68** [comment]
I found the problem, duplicate CSS. I need to go over the CSS file for foreground. Maybe time to break it up. 

- Foundation overrides
- MW specific overrides
- Extension overrides

One more time, pull down develop branch. 🤞

**Comment by kghbln** [comment]
> One more time, pull down develop branch. :crossed_fingers:

Done!

**Comment by Hutchy68** [comment]
So close!

**Comment by kghbln** [comment]
> So close!

Yay! :) Thanks a lot for your effort!
