### ISSUE TITLE
FoUC (Flash of Unstyled Content) Issue

### ISSUE THREAD

**Issue by Hutchy68** [thingles/foreground#301]
I am putting this here as a reminder for documentation and it should be added as a FAQ when v2.0 is released.

There is a FoUC issue which I could only see on a website with Semantic MediaWiki enabled. Nearly drove me over the edge last night as to why it was only an issue on SMW enabled sited. I have tracked it down to the way MW blocks system message enabled CSS. MW tests pages (probably not ideal way) to block CSS from what they determine are "Restricted Pages" (Login, User Prefs, etc). 

For some reason (extra load? of SMW) changing the CSS of a website using Foreground will cause a FoUC. Navbar color for example will load as the default and milliseconds later change to the colors set by MediaWiki:Foreground.css or User:Username/foreground.css. It is definitely noticeable and quite annoying. It also limits the way a user can style their site using Foreground, eg. changing the navbar color.

`$wgAllowSiteCSSOnRestrictedPages = true;` must be set to true and the FoUC stops completely. Personally, I thought that was one of the stupidest merges into the MW core. The reasoning was borderline paranoia. Many people complained and the `$wgAllowSiteCSSOnRestrictedPages = true;` was created as an option which is set to `false` as a default. Anyway, anyone using a custom skin should have this set to `true` in my opinion.

**Comment by kghbln** [comment]
CSS blocking was a MW 1.23.3? change to prevent execution of scripts injected via CSS on pages with sensitive data (=security change). `$wgAllowSiteCSSOnRestrictedPages = true;` indeed overrides the blocking of CSS on restricted page.

Semantic MediaWiki uses auto loading triggered by Composer so this may be the reason for the delay in loading observed. Not sure though.

This setting is set to "`true`" on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Main_Page).

**Comment by Hutchy68** [comment]
Closing as answered and won't fix. MW setting fixes issue.
