### ISSUE TITLE
`wikiNameDesktop` configuration option

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#306]
Pivot is providing a `wikiNameDesktop` configuration option which I think is a nice to have enhancement for Foreground, too.

**Comment by Hutchy68** [comment]
Foreground already has `wikiName => 'Alternate WikiName'` as a feature. The issue is, Foreground has limited title space even on desktop. For Semantic-MediaWiki Sandbox you could use -> `wikiName => 'SMW Sandbox'` and that would look better.

**Comment by kghbln** [comment]
Ah, ok, yeah, affirmative. So it does not really make sense to differentiate between mobile and desktop. I remember that I reduced the font since on some occasions where a shorter name did not fit.

Thanks for the suggestion!
