### ISSUE TITLE
Remove bogus tags

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#309]
I just ran into the issue when "upgrading" to "v2.0.0-beta1" which was shown with `git tag -l`. Apparently this was a downgrade and the wiki was bellies up. Same for the "v1.0IconBeta" tag. Both of them confuse more than they help.

What I actually wanted to do was `git checkout origin/develop` instead of `git checkout origin/v2.0.0-beta1` :)

**Comment by Hutchy68** [comment]
Ok, I’ll take a look at it and fix the release. Thanks!

**Comment by Hutchy68** [comment]
Ok, all tags not relevant are removed. v2.1.0-alpha is technically the correct release for the develop branch. Asked for feedback on this branch and want to push this to a finally release by end of Oct. Closing this issue.
