### ISSUE TITLE
Integration with VisualEditor

### ISSUE THREAD

**Issue by kghbln** [thingles/foreground#313]
### Setup

- Browsers and versions: Fx 58
- MediaWiki version: MW 1.27.4
- Database version: MariaDB 10.1.26 
- PHP version: 7.0.27
- Foreground version: 2.1.0-beta (2d10e18)
- Extension version (if connected to the issue): VisualEditor 0.1.0 (9da5996)

### Issue

I have now installed the VisualEditor on [forground.wikiproject.net](https://foreground.wikiproject.net/wiki/Special:Version) Two things do not work well:

1) When [editing a page](https://foreground.wikiproject.net/wiki/List_of_help_pages?veaction=edit) the category gets relocated

2) When [creating a page](https://foreground.wikiproject.net/wiki/New_Page?veaction=edit) the page title gets relocated.

I have seen this. Perhaps [this offers a solution?](https://github.com/Wiki-Org/Forground-VisualEditor-patch)

**Comment by Hutchy68** [comment]
It looks like the page title is ok, just not a match of this with an line under the Page Title. 

![image](https://user-images.githubusercontent.com/3527469/36098583-762dd736-0fcd-11e8-8a6e-2a3bb5d55705.png)

Catlinks is hidden in an activated VE, must be a js callback to add a hidden class. Anyway, this CSS...

```
.ve-activated #catlinks {
    display:none;
}
.ve-activated #firstHeading {
    border-bottom:  1px solid #ccc;
    padding: 0 0 5px;
}

.ve-activated [class*="mw-content-"] {
    padding: 0;
}
```
Should fix the styling of VE.
## Editing
![image](https://user-images.githubusercontent.com/3527469/36099005-13988614-0fcf-11e8-953c-a10f36b17cbe.png)
## Creating a new page
![image](https://user-images.githubusercontent.com/3527469/36099212-c54b30a0-0fcf-11e8-9f44-7c59ed688141.png)

**Comment by kghbln** [comment]
And I was wondering why you did not add the CSS yourself....

Yeah, 2) looks alrighty now. Should this go into the CSS served already by Foreground?

About 1) You are right. Basically it is working as expected. It looked a bit wrong but I just checked that this is indeed intended to be like this. Admittedly I hardly use VE so I got confused.

Thanks a lot!

**Comment by Hutchy68** [comment]
It will have to be added to `foreground.css`. Some of the issues - VE is in perpetual development so there could have been some breaks not picked up on.

**Comment by Hutchy68** [comment]
Fixed, closing. Thanks for reporting!

**Comment by kghbln** [comment]
Wow, cool. Thanks a ton!
