### ISSUE TITLE
Better styling for TOC

### ISSUE THREAD

**Issue by thingles** [thingles/foreground#40]
I don't use table of contents very often (**TOC**) but it is used and it's a nice capability. Can we get some better default styling for it in Foreground? See example

http://bodwiki.com/wiki/BODWiki:Frequently_Asked_Questions

table's of class "toc"

**Comment by Hutchy68** [comment]
Closing as fixed. Added enough CSS to style TOCs better. No float, light border, heading size, etc. The final style should be up to the wiki using Foreground.
