### ISSUE TITLE
Alignment on UserLogin page broken

### ISSUE THREAD

**Issue by apinrise** [thingles/foreground#67]
The two column view on in Foreground is broken.
The rightmost column sinks below the left, as seen here:
http://ingemorath.org/wiki/index.php?title=Special:UserLogin&&type=signup
but should appear like how it does on mediawiki.org:
https://www.mediawiki.org/w/index.php?title=Special:UserLogin&type=signup

**Comment by Hutchy68** [comment]
Closing, almost 3 years old with no response.

Reopen if needed
