### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by thingles** [thingles/foreground#82]
Newest code with Foundation 5.1 made tabs stop working on WikiApiary. Looked at this briefly but wasn't obvious what the issue was. I reverted back to a442d1c14d07df1c38c0932bae6a345eab07c2a8. /cc @garrickvanburen

**Comment by paladox** [comment]
Is this still a problem. @Hutchy68 where we merged the update in develop branch the tabs code update wasent included.

**Comment by Hutchy68** [comment]
Didn't add it on purpose. Need to have a security discussion.

**Comment by paladox** [comment]
Oh ok. Why not just keep the section js even though it is made for foundation 4 we could tweak the file to work with foundation 5. It would make the migration quicker for wikiapriary.

**Comment by paladox** [comment]
I get this error

Object doesn't support property or method 'outerHeight'

inside foundation.section.js file in foundation 5.

**Comment by Hutchy68** [comment]
Merged into skin code. New feature `'enableTabs' => true` will allow new tabs markup to be used in wiki pages. Default set to `false`.
