### ISSUE TITLE
Act-button dropdown often leaves the screen on 'mouseenter' in small browser's window 

### ISSUE THREAD

**Issue by HiRolla** [thingles/foreground#89]
I think, there is unreasonable diff in positions of dropdown whether act-button was pressed or just reached by mouse. 
Source code is complicated because of that, and sometimes the positioning of dropdown gives unpredictable results (i.e. different results or even no result after the equal clicks or moves).  

I didn't find out how to make dropdown to appear always at the same position (relative to the act-btn, and without '785px' screen violations). So, for a while, i switched off the 'mouseenter' event-handler, got only clicks/taps working and got rid of needless horisontal scrollbar rises.

**Comment by Hutchy68** [comment]
I have only seen this on browser re-sizing and is v1.x.x specific. Will not be an issue in V2.x.x. Using the native on mouseover. No issues reported

Closing.
